### ISSUE TITLE
[FEATURE] Remove Partner TopSite 

### ISSUE THREAD

**Issue by cnevinc** [RocketScientists/Rocket#27]
**User story**
As a user, I would like to freely use my browser without any default top sites and use/remove whatever top sites I want.

**Acceptance Criteria (how do I know when I’m done?)** 
1. Remove the onboarding for top site selection
2. Remove the constrain where users can't remove default top sites.

**Additional context**
We don't have partners now. And we may never will. We should/could at least don't show the partner-facing features.

**Comment by walkingice** [comment]
the fixed top sites were removed in https://github.com/RocketScientists/Rocket/commit/e132fce2e14c969ee3dfa8d154db15b4ae9c7481
