### ISSUE TITLE
Icon & Logo redesign

### ISSUE THREAD

**Issue by benjamin-cheng** [RocketScientists/Rocket#5]
Launcher icon:
Release => https://github.com/RocketScientists/Rocket/blob/master/app/src/main/res/mipmap-xxhdpi/ic_launcher.png

Preview => https://github.com/RocketScientists/Rocket/blob/master/app/src/preview/res/mipmap-xxhdpi/ic_launcher.png

Logo:
Home/About page/Private mode => https://github.com/RocketScientists/Rocket/blob/master/app/src/main/res/drawable-xxhdpi/ic_firefox_lite_logo.png

**Comment by youwenliang** [comment]
Logo: 
![ic_firefox_lite_logo](https://user-images.githubusercontent.com/8919308/91187353-a7e61700-e722-11ea-87bd-d1fe98e9fc15.png)

**Comment by benjamin-cheng** [comment]
Updated the logo in the PR
https://github.com/RocketScientists/Rocket/pull/1/commits/76d70496689a6c5b7e4d139cbc3e1d52e0e718bd?short_path=02766c8#diff-02766c8160ad68bc84e59766a90abfa4
