### ISSUE TITLE
[FEATURE] be able to pin websites that are not in the list

### ISSUE THREAD

**Issue by franco27** [RocketScientists/Rocket#73]
hello
we still cannot add a personalized URL to the home page of your internet browser.

 being able to pin any website to the browser's start page would have been a great feature. it's very regrettable
version 2.7.x

![CollageMaker_20211107_085437026](https://user-images.githubusercontent.com/31793920/140637082-f66232ed-56a3-4b0a-b986-edc37720db44.jpg)

**Comment by walkingice** [comment]
thank you for reporting this. I totally agree with you.

Actually I have a local dirty patch to do this, because I do need this feature too.

In 2.7 release we are focusing on Multiple Private tab feature. I will implement this to next feature release.

**Comment by franco27** [comment]
Thank you for your reply

**Comment by walkingice** [comment]
https://user-images.githubusercontent.com/54793/144442707-62ef5a7c-6c3a-40db-8df5-f0279f2e72d0.mp4

I just implemented this feature, and it is expected to be included in next release

**Comment by franco27** [comment]
Thank you a lot
